version: '3.8'

services:
  postgres:
    container_name: microstakes-postgres
    image: postgres:15
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_MULTIPLE_DATABASES: micro_stakes_keycloak
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - microstakes_postgres_data:/var/lib/postgresql/data

  keycloak:
    container_name: microstakes-keycloak
    image: quay.io/keycloak/keycloak:22.0
    environment:
      KEYCLOAK_ADMIN: '${KEYCLOAK_ADMIN_USER}'
      KEYCLOAK_ADMIN_PASSWORD: '${KEYCLOAK_ADMIN_PASSWORD}'
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/micro_stakes_keycloak
      KC_DB_USERNAME: '${DB_USER}'
      KC_DB_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    command: start-dev

  app:
    container_name: microstakes-app
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_NAME: '${DB_NAME}'
      KEYCLOAK_URL: http://keycloak:8081
      KEYCLOAK_REALM: '${KEYCLOAK_REALM}'
      KEYCLOAK_CLIENT_ID: '${KEYCLOAK_CLIENT_ID}'
      KEYCLOAK_CLIENT_SECRET: '${KEYCLOAK_CLIENT_SECRET}'
      KEYCLOAK_ADMIN_USER: '${KEYCLOAK_ADMIN_USER}'
      KEYCLOAK_ADMIN_PASSWORD: '${KEYCLOAK_ADMIN_PASSWORD}'
    depends_on:
      - postgres
      - keycloak

volumes:
  microstakes_postgres_data: